### ISSUE TITLE
Add chocolatey program

### ISSUE THREAD

**Issue by llHoYall** [llHoYall/hConfig#3]
## ToDo

* [x] Add chocolatey for windows
* [x] Add install feature
* [x] Add upgrade feature
* [x] Add config feature
