### ISSUE TITLE
Add font feature

### ISSUE THREAD

**Issue by llHoYall** [llHoYall/hConfig#6]
## ToDo

* [x] Add FontUI (for Windows)
* [x] Add install feature
* [x] Add upgrade feature
* [x] Add uninstall feature
* [x] Add config feature

**Comment by llHoYall** [comment]
Resolved
